name: IntelliCode Team Completions training

on: [push, pull_request]

jobs:
  training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: IntelliCode Team Completions
        uses: microsoft/vs-intellicode@v1.0
    
